[package]
name = "ffmpeg-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
egui-sfml = { git = "https://github.com/crumblingstatue/egui-sfml.git" }
libmpv-sys = { git = "https://github.com/crumblingstatue/libmpv-rs.git", features = ["use-bindgen"] }
rand = "0.8.5"
rfd = "0.12.0"
sfml = { git = "https://github.com/jeremyletang/rust-sfml.git" }
shell-words = "1.1.0"
thiserror = "1.0.31"
